# Generated by Django 4.2.3 on 2023-11-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add an additional bed type
    """

    dependencies = [("cms", "0002_use_timetrvel_time")]

    operations = [
        migrations.AlterField(
            model_name="bed",
            name="bed_type",
            field=models.CharField(
                choices=[("normal", "normal"), ("small", "small")],
                help_text="specialty bed types may be available",
                max_length=10,
                verbose_name="bed type",
            ),
        )
    ]
