# Generated by Django 4.2.3 on 2023-11-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Fix admission/discharge date fields, which should be DateTime instead of just Date
    """

    dependencies = [("cms", "0003_add_bed_type")]

    operations = [
        migrations.AlterField(
            model_name="bedassignment",
            name="admission_date",
            field=models.DateTimeField(
                blank=True,
                help_text="date the hostpital stay begins",
                verbose_name="admission date",
            ),
        ),
        migrations.AlterField(
            model_name="bedassignment",
            name="discharge_date",
            field=models.DateTimeField(
                blank=True,
                help_text="date the hospital stay ends",
                null=True,
                verbose_name="discharge date",
            ),
        ),
    ]
