# Generated by Django 4.2.3 on 2023-12-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add a user setting for the ward view mode
    """

    dependencies = [("cms", "0004_fix_admission_and_discharge_dates")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ward_as_timeline",
            field=models.BooleanField(default=False),
        )
    ]
