# Generated by Django 4.2.3 on 2024-01-12 08:42

from django.db import migrations


class Migration(migrations.Migration):
    """
    Add "add_user" permission to user model
    """

    dependencies = [("cms", "0005_add_ward_mode_setting")]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "ordering": ["personnel_id"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        )
    ]
