# Generated by Django 4.2.3 on 2024-01-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add another medical record type
    """

    dependencies = [("cms", "0006_alter_user_permissions")]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("intake", "patient intake form"),
                    ("note", "note"),
                    ("lab", "lab report"),
                ],
                help_text="type of this record",
                max_length=32,
                verbose_name="record type",
            ),
        )
    ]
