# Generated by Django 4.2.3 on 2024-01-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add a new bed type
    """

    dependencies = [("cms", "0007_add_record_type")]

    operations = [
        migrations.AlterField(
            model_name="bed",
            name="bed_type",
            field=models.CharField(
                choices=[
                    ("normal", "normal"),
                    ("small", "small"),
                    ("ventilator", "with ventilator"),
                ],
                help_text="specialty bed types may be available",
                max_length=10,
                verbose_name="bed type",
            ),
        )
    ]
