# Generated by Django 4.2.3 on 2024-01-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Rename the discharge date field to estimated discharge date
    """

    dependencies = [("cms", "0008_add_bed_type")]

    operations = [
        migrations.AlterField(
            model_name="bedassignment",
            name="discharge_date",
            field=models.DateTimeField(
                blank=True,
                help_text="date the hospital stay is estimated to end",
                null=True,
                verbose_name="estimated discharge date",
            ),
        )
    ]
